// Expanded lists of design concepts
export const styles = [
  'minimalist',
  'abstract',
  'geometric',
  'typographic',
  'vintage',
  'flat design',
  '3D',
  'hand-drawn',
  'futuristic',
  'organic',
  'grunge',
  'pop art',
  'retro',
  'line art',
  'monochrome',
  'watercolor',
  'gradient',
  'low poly',
  'isometric',
  'negative space',
  'cartoonish',
  'steampunk',
  'cyberpunk',
  'art deco',
  'calligraphy',
  'pixel art',
  'surreal',
  'collage',
  'graffiti',
  'baroque',
  'glitch',
  'psychedelic',
  'minimal line',
  'doodle',
  'clay',
  'digital painting',
  'photorealistic',
  'charcoal sketch',
  'stencil',
  'mosaic',
];

export const colors = [
  'monochrome colors',
  'vibrant colors',
  'pastel colors',
  'neon colors',
  'earth tones',
  'black and white',
  'primary colors',
  'duotone',
  'analogous colors',
  'complementary colors',
  'metallic colors',
  'gradient colors',
  'rainbow colors',
  'cool colors',
  'warm colors',
  'muted colors',
  'sepia tones',
  'jewel tones',
  'fluorescent colors',
  'tinted colors',
  'iridescent colors',
  'bronze tones',
  'silver tones',
  'golden hues',
  'copper shades',
];

export const techniques = [
  'bold lines',
  'thin lines',
  'shadows',
  'embossed effect',
  'glossy finish',
  'matte finish',
  'texture overlay',
  'patterned background',
  'transparent background',
  'gradient overlay',
  'double exposure',
  'halftone effect',
  'motion blur',
  'vignette',
  'lens flare',
  'duotone effect',
  'low poly effect',
  'wireframe',
  'vector art',
  'silhouette',
  'parallax effect',
  'long shadow',
  'bokeh effect',
  'pixelation',
  'fragmentation',
  'light painting',
  'chromatic aberration',
  'paper cutout',
  'photomontage',
  'smoke effect',
];

export const shapes = [
  'circles',
  'squares',
  'triangles',
  'hexagons',
  'spirals',
  'waves',
  'arrows',
  'stars',
  'cubes',
  'spheres',
  'pyramids',
  'ribbons',
  'shields',
  'abstract shapes',
  'organic shapes',
  'gears',
  'network nodes',
  'infinite loops',
  'circuit patterns',
  'atomic structures',
  'feathers',
  'leaves',
  'animals',
  'mountains',
  'lattice patterns',
  'clouds',
  'wings',
  'compass',
  'maze',
  'radiant lines',
];

export const fonts = [
  'sans-serif font',
  'serif font',
  'script font',
  'handwritten font',
  'bold font',
  'light font',
  'italic font',
  '3D text',
  'vintage font',
  'modern font',
  'decorative font',
  'typewriter font',
  'graffiti font',
  'calligraphy font',
  'stencil font',
  'neon font',
  'block letters',
  'outline font',
  'pixelated font',
  'geometric font',
  'gothic font',
  'cursive font',
  'monospaced font',
  'chalk font',
  'comic font',
];

export const themes = [
  'technology',
  'innovation',
  'growth',
  'connectivity',
  'speed',
  'security',
  'simplicity',
  'global',
  'eco-friendly',
  'futuristic',
  'trustworthy',
  'professional',
  'friendly',
  'cutting-edge',
  'creative',
  'dynamic',
  'modern',
  'sleek',
  'elegant',
  'powerful',
  'luxury',
  'adventure',
  'health',
  'education',
  'entertainment',
  'sporty',
  'artistic',
  'industrial',
  'nature-inspired',
  'minimalist',
];
